### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by vik-y** [zense/helpful-resources#4]
First of all - great idea. There are tons of resources lying around the internet for everything. Compiling them together is definitely a win win for everyone.

I have just one suggestion here - don't leave the files empty, rather have a template so that people follow a structure. For instance this file is empty https://github.com/zense/helpful-resources/blob/main/web-dev/RESOURCES.md - having a template makes it easier for everyone.

**Comment by vijay-jaisankar** [comment]
Thanks a lot for the suggestion @vik-y 

Will do.

**Comment by vijay-jaisankar** [comment]
https://github.com/zense/helpful-resources/pull/5
